In [2]:
import numpy as np

In [ ]:
1. Write a Python Program to Add Two Matrices?
2. Write a Python Program to Multiply Two Matrices?
3. Write a Python Program to Transpose a Matrix?
4. Write a Python Program to Sort Words in Alphabetic Order?
5. Write a Python Program to Remove Punctuation From a String?

In [3]:
# 1.
A=np.random.randint(0,5,(3,3))
B=np.random.randint(5,11,(3,3))
print(A+B)

[[ 7  8  8]
 [ 8 11 12]
 [ 9  7 10]]


In [4]:
# 2.
A=np.random.randint(0,5,(3,3))
B=np.random.randint(5,11,(3,3))
print(A@B)


[[72 76 96]
 [48 45 60]
 [50 53 58]]


In [5]:
# 3.
A=np.random.randint(0,5,(3,3))
A

array([[2, 2, 2],
       [3, 1, 2],
       [4, 4, 2]])

In [6]:
A.T

array([[2, 3, 4],
       [2, 1, 4],
       [2, 2, 2]])

In [7]:
# 4.
st=str(input())
words=st.split()
words.sort()

for i in words:
    print(i)

how are u
are
how
u


In [22]:
# 5.
s="how ,beautiful@> she is!"
l='''!'",@>'''
for i in s:
    if i in l:
        s=s.replace(i,"")
        
print(s)

how beautiful she is
